### ISSUE TITLE
Global vehicle blacklist only works for first vehicle

### ISSUE THREAD

**Issue by P4R4NORM4L** [MrGriefs/dynamicblacklist#1]
Setting up the config is pretty straight forward, un but I can only block the first vehicle in the list
`['vehicles'] = {
        -- vehicles that are locked for everyone (including admins)
        'stockade3',
        'banshee2',`
I can spawn in the banshee2 but not the stockade, is there anyway I can fix this ?

**Comment by MrGriefs** [comment]
Does the message stating that the vehicle is blacklisted not appear when you enter it as the driver?

**Comment by P4R4NORM4L** [comment]
No it does not but it does for the stockade So I know it's loaded and working I did how ever change a bit of to show the name of the vehicle but thats about it
I added the Variable Car and added it to the message

`if veh and DoesEntityExist(veh) then
            local hash = GetEntityModel(veh)
            local driver = GetPedInVehicleSeat(veh, -1)
            local Car = GetDisplayNameFromVehicleModel(hash)
            if not VehicleDriverBlacklist or driver == ped then
                local confirm = ClientBlacklist.vehicles[hash]
                if Inverted then confirm = not confirm end
                if confirm then
                    DeleteEntity(veh)
                    ClearPedTasksImmediately(ped)
                    ShowNotification("~y~Hey!~s~ You do not have permission to use this vehicle! ( " .. Car .. " )")
                end
            end
        end`
Like I said it works for the stockade3 but not for the banshee

**Comment by MrGriefs** [comment]
What happens if you move `banshee2` above `stockade3` in the array?

**Comment by P4R4NORM4L** [comment]
> What happens if you move `banshee2` above `stockade3` in the array?

Still the same, still not able to remove banshee2 but stockade works. Maybe it's not finding the hash ?

**Comment by MrGriefs** [comment]
Silly questions, but did you perhaps:
* misspell it,
* didn't reload the resource or
* edit vital functions with `client.lua`?

Also, don't forget to check F8 for logged errors.

**Comment by P4R4NORM4L** [comment]
I looked in the vehicles.lua and both vehicles are listed there with the correct hashes.

In the F8 I get an error in client.lua on line 43 attempt to concatenate a boolean value (local confirm)

**Comment by P4R4NORM4L** [comment]
I only added this 
`local Car = GetDisplayNameFromVehicleModel(hash)`
and changed the ShowNotification text
 thats all

**Comment by MrGriefs** [comment]
That appears to be an error occurring from the edits you have made. There is no concatenation in `client.lua`.

**Comment by P4R4NORM4L** [comment]
Ok i undid my changes let me see if it works

**Comment by P4R4NORM4L** [comment]
same issue no errors in f8

**Comment by P4R4NORM4L** [comment]
oh man 
I think I know what happened I was editing the file on my hdd and not the server I'm a dumbass let me check again

**Comment by P4R4NORM4L** [comment]
I can confirm i'm a dumbass ! It works  Sorry to bother you.

**Comment by MrGriefs** [comment]
No problem. I'm glad the issue is sorted.  
If the problem is still occurring, you can reopen this issue.
