### ISSUE TITLE
Can't get it to work again

### ISSUE THREAD

**Issue by P4R4NORM4L** [MrGriefs/dynamicblacklist#3]
So i've updated the vehicle list because it was out of date but, I cannot get the vehicles to be restricted.

**Comment by MrGriefs** [comment]
Further information is required.

**Comment by P4R4NORM4L** [comment]
ok so I updated the vehicle list to the newest one because the list was missing certain vehicles I thought that was the issue causing the problem but even though i don't have have the permission dblacklist.owner granted i can still use the dblacklist.owner vehicles.

this is my config 
`Restricted = {
    ['vehicles'] = {
        -- vehicles that are locked for everyone (including admins)
        'banshee2',
        'stockade3',
        
        -- vehicles only admins can use
        ['owner'] = {
            'phantom2',
            'hauler2',
            'cerberus',
            'cerberus2',
            'cerberus3',
            'dinghy5',
            'kosatka',
            'patrolboat',
            'tug',
            'boxville5',
            'handler',
            'bruiser',
            'bruiser2',
            'bruiser3',
            'caracara',
            'dune3',
            'insurgent',
            'insurgent3',
            'marshall',
            'menacer',
            'monster',
            'monster3',
            'monster4',
            'monster5',
            'nightshark',
            'technical',
            'technical2',
            'technical3',
            'kuruma2',
            'schafter5',
            'oppressor',
            'oppressor2',
            'vigilante',
            'voltic2',
            'scramjet',
            'brickade',
            'dukes2',
            'trailerlarge',
            'apc',
            'barrage',
            'chernobog',
            'halftrack',
            'khanjali',
            'rhino',
            'scarab',
            'scarab2',
            'scarab3',
            'thruster',
            'trailersmall2',
            'pounder2',
            'terbyte',
            'ambulance',
            'fbi',
            'fbi2',
            'firetruk',
            'lguard',
            'pbus',
            'police',
            'police2',
            'police3',
            'police4',
            'policeb',
            'policeold1',
            'policeold2',
            'policet',
            'polmav',
            'pranger',
            'predator',
            'riot',
            'riot2',
            'sheriff',
            'sheriff2',
            'alphaz1',
            'avenger',
            'avenger2',
            'besra',
            'blimp',
            'blimp2',
            'blimp3',
            'bombushka',
            'cargoplane',
            'cuban800',
            'dodo',
            'duster',
            'howard',
            'hydra',
            'jet',
            'lazer',
            'luxor',
            'luxor2',
            'mammatus',
            'microlight',
            'miljet',
            'mogul',
            'molotok',
            'nimbus',
            'nokota',
            'pyro',
            'rogue',
            'seabreeze',
            'shamal',
            'starling',
            'strikeforce',
            'stunt',
            'titan',
            'tula',
            'velum',
            'velum2',
            'vestra',
            'volatol',
            'akula',
            'annihilator',
            'buzzard',
            'buzzard2',
            'cargobob',
            'cargobob2',
            'cargobob3',
            'cargobob4',
            'frogger',
            'frogger2',
            'havok',
            'hunter',
            'maverick',
            'polmav',
            'savage',
            'seasparrow',
            'skylift',
            'supervolito',
            'supervolito2',
            'swift',
            'swift2',
            'valkyrie',
            'valkyrie2',
            'volatus',
            'rumpo3',
            'rebel',
            'zr380',
            'zr3802',
            'zr3803',
            'dominator4',
            'dominator5',
            'dominator6',
            'ruiner2',
            'tampa3',
            'baller5',
            'baller6',
            'contender',
            'xls2',
            'cog552',
            'cognoscenti2',
            'limo2',
            'schafter6',
            'cablecar',
            'freight',
            'freightcar',
            'freightcont1',
            'freightcont2',
            'freightgrain',
            'metrotrain',
            'tankercar',
        },
        -- vehicles only moderators (and above) can use
        ['leo'] = {
            'code310char',
            'code314char',
            'code314taho',
            'code316impa',
            'code318char',
            'code318taho',
            'code320exp',
            'code3camero',
            'code3cap',
            'code3silver',
            'code3cvpi',
            'code3f150',
            'code3gator',
            'code3mustan',
            'code3ram',
            'code3fpis',
            'sheriff',
            'sheriff2',
            'chgr',
            'cvpi',
            'durango',
            'ram',

        },
        ['construction'] = {
            'bulldozer',
            'cutter',
            'dump',

        },
        ['snowvehicles'] = {
            'burrito5',
            'tractor3',
            'sadler2',
            'stockade3',
            'rancherxl2',
            'mesa2',
            'asea2',
            'emperor3',
        },
    },`

**Comment by MrGriefs** [comment]
The following will be useful to diagnose the problem;

- Full `config.lua`
- Are you using the latest commit (not latest release)?
- What edits have you made to source files?

**Comment by P4R4NORM4L** [comment]
does the permission have to be:
add_aced group.owner blacklist.vehicles.owner allow?

**Comment by P4R4NORM4L** [comment]
full config
[config.txt](https://github.com/MrGriefs/dynamicblacklist/files/7263306/config.txt)

I think i'm using latest release not commit, only thing I added we're the vehicles you can look at github fork

**Comment by MrGriefs** [comment]
- `add_ace group.owner dblacklist.owner allow` - for all categories
- `add_ace group.owner dblacklist.owner.vehicles allow` - for only vehicles
- `add_ace group.owner dblacklist.owner.peds allow` - for only peds
- `add_ace group.owner dblacklist.owner.weapons allow` - for only weapons

Remember, the prefix is `dblacklist` unless changed.

**Comment by P4R4NORM4L** [comment]
yes did not change prefix and this is what I have as permissions
add_ace group.owner dblacklist.owner allow

**Comment by MrGriefs** [comment]
I would recommend using the latest commit as the latest release is 7 commits behind, and there's been a few fixes which may affect the issue you're experiencing.

**Comment by P4R4NORM4L** [comment]
oh ok let me download it real quick

**Comment by P4R4NORM4L** [comment]
I'll have to edit my config it's take me a minute to reflect the changes

**Comment by P4R4NORM4L** [comment]
I can remove the weapons example section ?

**Comment by MrGriefs** [comment]
The `WEAPONS_EXAMPLE` variable is unused and will be removed in a refactor.

**Comment by P4R4NORM4L** [comment]
ok

**Comment by P4R4NORM4L** [comment]
updated and still not working! should i Deny the other groups or just not granting them access should be sufficient

**Comment by P4R4NORM4L** [comment]
would you want to get in a call with me on discord ?

**Comment by P4R4NORM4L** [comment]
so i can screen share

**Comment by MrGriefs** [comment]
Sure can do, DM me [`Griefs#9476`](https://discord.com/channels/@me/291656468493631488)

**Comment by P4R4NORM4L** [comment]
why in the fxmanifest are the vehicles and weapon files not listed?
